index:
   path: /
   controller: App\Controller\SecurityController::login
login:
  path: /login
  controller: App\Controller\SecurityController::login
logout:
  path: /logout
  controller: App\Controller\SecurityController::logout  
# products_stock:
#     path: /products/{id}/stock/
#     defaults:
#         _controller: App\Controller\ProductsController::stock 