App\Entity\Products:
    type: entity
    table: products
    indexes:
        categoria_id:
            columns:
                - categoria_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        stock:
            type: integer
            nullable: false
            options:
                unsigned: false
    manyToOne:
        categoria:
            targetEntity: Categories
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                categoria_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
